### ISSUE TITLE
Include event timestamp in DATA extension

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-sse.java#13]
Include event timestamp as follows:
```
struct SseDataEx
{
...
    long timestamp;
...
}
```
which is encoded as a `timestamp` field with hex value along with the event.
```
data:example\n
timestamp:0x1619fe172c7\n
\n
```

As this is a non-standard extension to Server-Sent Events, the client should explicitly opt-in via an extended `accept` header.
```
accept:text/event-stream;ext=timestamp
```

**Comment by dpwspoon** [comment]
resolved by https://github.com/reaktivity/nukleus-sse.java/pull/14

**Comment by dpwspoon** [comment]
Completed by above PR
